server:
  port: 8082
  host: localhost
  error:
    include-stacktrace: always
swagger:
  port: 8082
spring:
  application:
    name: 'StatistiquesCDI'
  profiles:
    active: prod
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    com.o2.iris.territoryallocation: DEBUG
